name: laravel-rules-to-schema
type: laravel
docroot: "workbench/public"
php_version: "8.2"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: postgres
    version: "16"
upload_dirs:
    - ../storage
    - ../../temp
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: auto
corepack_enable: false
